import { HotelState } from '../types';

export const DEMO_STATE: HotelState = {
  rooms: [
    {
      id: '101',
      name: 'Room 101',
      floor: 1,
      type: 'Skyview Suite',
      pricePerNight: 4500,
      status: 'active',
      housekeepingStatus: 'ready',
      amenities: ['AC', 'WiFi', 'TV', 'Hot Water'],
      publicDescription: 'Cozy room with garden view. Perfect for a quiet stay.',
    },
    {
      id: '102',
      name: 'Room 102',
      floor: 1,
      type: 'Skyview Suite',
      pricePerNight: 4500,
      status: 'active',
      housekeepingStatus: 'dirty',
      amenities: ['AC', 'WiFi', 'TV', 'Hot Water'],
    },
    {
      id: '201',
      name: 'Room 201',
      floor: 2,
      type: 'Sunset Room',
      pricePerNight: 7500,
      status: 'active',
      housekeepingStatus: 'ready',
      amenities: ['AC', 'WiFi', 'TV', 'Hot Water', 'Mini Fridge', 'Balcony'],
      publicDescription: 'Deluxe room with mountain view balcony.',
    },
    {
      id: '202',
      name: 'Room 202',
      floor: 2,
      type: 'Sunset Room',
      pricePerNight: 7500,
      status: 'active',
      housekeepingStatus: 'ready',
      amenities: ['AC', 'WiFi', 'TV', 'Hot Water', 'Mini Fridge'],
    },
    {
      id: '301',
      name: 'Suite 301',
      floor: 3,
      type: 'Family Haven',
      pricePerNight: 14000,
      status: 'active',
      housekeepingStatus: 'ready',
      amenities: ['AC', 'WiFi', 'TV', 'Hot Water', 'Kitchenette', 'Balcony', 'Bathtub', 'Lounge Area'],
      publicDescription: 'Premium family suite with panoramic valley views.',
    },
    {
      id: '302',
      name: 'Suite 302',
      floor: 3,
      type: 'Family Haven',
      pricePerNight: 14000,
      status: 'maintenance',
      housekeepingStatus: 'cleaning-started',
      amenities: ['AC', 'WiFi', 'TV', 'Hot Water', 'Kitchenette', 'Balcony'],
    },
    {
      id: '401',
      name: 'Penthouse',
      floor: 4,
      type: 'Skyview Suite',
      pricePerNight: 28000,
      status: 'active',
      housekeepingStatus: 'ready',
      amenities: ['AC', 'WiFi', 'Smart TV', 'Hot Water', 'Full Kitchen', 'Private Terrace', 'Jacuzzi'],
      publicDescription: 'Exclusive rooftop penthouse with 360° views.',
    },
  ],
  guests: [
    {
      id: 'GST-001',
      firstName: 'Ahmed',
      lastName: 'Siddiqui',
      phone: '+923001234567',
      email: 'ahmed@example.com',
      cnic: '42201-1234567-1',
      createdAt: '2025-10-01T10:00:00Z',
      documentType: 'cnic',
      documentNumber: '42201-1234567-1',
      profileStatus: 'vip',
      notes: 'Prefers high floor. Repeat guest.',
    },
    {
      id: 'GST-002',
      firstName: 'Sara',
      lastName: 'Khan',
      phone: '+923331234567',
      email: 'sara.khan@example.com',
      cnic: '35202-7654321-2',
      createdAt: '2025-11-15T08:30:00Z',
      documentType: 'cnic',
      documentNumber: '35202-7654321-2',
      profileStatus: 'standard',
    },
    {
      id: 'GST-003',
      firstName: 'Bilal',
      lastName: 'Mirza',
      phone: '+923211234567',
      email: 'bilal.m@example.com',
      cnic: '42301-9876543-3',
      createdAt: '2025-12-01T12:00:00Z',
      documentType: 'cnic',
      documentNumber: '42301-9876543-3',
      profileStatus: 'standard',
    },
    {
      id: 'GST-004',
      firstName: 'Maria',
      lastName: 'Hussain',
      phone: '+923451234567',
      email: 'maria@example.com',
      cnic: '61101-1122334-4',
      createdAt: '2025-12-10T09:00:00Z',
      documentType: 'cnic',
      documentNumber: '61101-1122334-4',
      profileStatus: 'vip',
      notes: 'VIP corporate client. Early check-in preferred.',
    },
    {
      id: 'GST-005',
      firstName: 'James',
      lastName: 'Carter',
      phone: '+447700900123',
      email: 'j.carter@company.co.uk',
      cnic: 'UK-PASSPORT-001',
      createdAt: '2026-01-05T14:00:00Z',
      documentType: 'passport',
      documentNumber: 'UK-PASS-998877',
      profileStatus: 'standard',
      notes: 'International guest. Requires airport pickup.',
    },
  ],
  bookings: [
    {
      id: 'BKG-20251201-AAA001',
      roomId: '101',
      guestId: 'GST-002',
      guestFirstName: 'Sara',
      guestLastName: 'Khan',
      guestPhone: '+923331234567',
      guestCnic: '35202-7654321-2',
      checkInDate: '2026-06-25',
      checkOutDate: '2026-06-29',
      totalPrice: 18000,
      status: 'checked-in',
      bookingSource: 'direct',
      advanceReceived: 5000,
      paymentMethod: 'bank',
      paymentStatus: 'partial',
      guestCount: 2,
      notes: 'Birthday trip',
      checkInTime: '14:30',
      checkedInAt: '2026-06-25T14:30:00Z',
    },
    {
      id: 'BKG-20251201-AAA002',
      roomId: '201',
      guestId: 'GST-001',
      guestFirstName: 'Ahmed',
      guestLastName: 'Siddiqui',
      guestPhone: '+923001234567',
      guestCnic: '42201-1234567-1',
      checkInDate: '2026-06-27',
      checkOutDate: '2026-07-01',
      totalPrice: 30000,
      status: 'checked-in',
      bookingSource: 'direct',
      advanceReceived: 15000,
      paymentMethod: 'cash',
      paymentStatus: 'partial',
      guestCount: 2,
      notes: 'VIP guest — ensure balcony view room',
      checkInTime: '12:00',
      checkedInAt: '2026-06-27T12:00:00Z',
    },
    {
      id: 'BKG-20251201-AAA003',
      roomId: '301',
      guestId: 'GST-004',
      guestFirstName: 'Maria',
      guestLastName: 'Hussain',
      guestPhone: '+923451234567',
      guestCnic: '61101-1122334-4',
      checkInDate: '2026-06-28',
      checkOutDate: '2026-06-30',
      totalPrice: 28000,
      status: 'confirmed',
      bookingSource: 'booking.com',
      advanceReceived: 28000,
      paymentMethod: 'bank',
      paymentStatus: 'paid',
      guestCount: 3,
      externalReference: 'BDC-9987766',
    },
    {
      id: 'BKG-20251201-AAA004',
      roomId: '401',
      guestId: 'GST-005',
      guestFirstName: 'James',
      guestLastName: 'Carter',
      guestPhone: '+447700900123',
      guestCnic: 'UK-PASSPORT-001',
      checkInDate: '2026-07-01',
      checkOutDate: '2026-07-05',
      totalPrice: 112000,
      status: 'confirmed',
      bookingSource: 'airbnb',
      advanceReceived: 112000,
      paymentMethod: 'card',
      paymentStatus: 'paid',
      guestCount: 4,
      externalReference: 'ABB-8823451',
      specialRequest: 'Need airport pickup and champagne on arrival.',
    },
    {
      id: 'BKG-20251201-AAA005',
      roomId: '202',
      guestId: 'GST-003',
      guestFirstName: 'Bilal',
      guestLastName: 'Mirza',
      guestPhone: '+923211234567',
      guestCnic: '42301-9876543-3',
      checkInDate: '2026-06-20',
      checkOutDate: '2026-06-23',
      totalPrice: 22500,
      status: 'checked-out',
      bookingSource: 'whatsapp',
      advanceReceived: 22500,
      paymentMethod: 'easypaisa',
      paymentStatus: 'paid',
      guestCount: 2,
      checkInTime: '15:00',
      checkOutTime: '11:00',
      checkedInAt: '2026-06-20T15:00:00Z',
      checkedOutAt: '2026-06-23T11:00:00Z',
    },
    {
      id: 'BKG-PENDING-001',
      roomId: '102',
      guestId: 'GST-003',
      guestFirstName: 'Bilal',
      guestLastName: 'Mirza',
      guestPhone: '+923211234567',
      guestCnic: 'PUBLIC-REQUEST',
      checkInDate: '2026-07-05',
      checkOutDate: '2026-07-08',
      totalPrice: 13500,
      status: 'pending',
      bookingSource: 'direct',
      advanceReceived: 0,
      paymentMethod: 'cash',
      paymentStatus: 'unpaid',
      guestCount: 1,
      notes: 'Public website booking request',
    },
  ],
  expenses: [
    {
      id: 'EXP-001',
      title: 'Monthly Utilities (Electricity & Gas)',
      category: 'utilities',
      amount: 45000,
      date: '2026-06-01',
      status: 'paid',
      description: 'June billing cycle utilities',
    },
    {
      id: 'EXP-002',
      title: 'Fresh Linen & Towel Replacement',
      category: 'room-supplies',
      amount: 18500,
      date: '2026-06-05',
      status: 'paid',
      description: 'Replaced worn-out linens in all rooms',
    },
    {
      id: 'EXP-003',
      title: 'AC Servicing — Room 302',
      category: 'maintenance',
      amount: 8000,
      date: '2026-06-12',
      roomId: '302',
      status: 'pending',
      description: 'Compressor issue in Suite 302',
      maintenanceIssueId: 'MNT-001',
    },
    {
      id: 'EXP-004',
      title: 'Staff Salaries — June',
      category: 'staff',
      amount: 120000,
      date: '2026-06-30',
      status: 'pending',
      description: '5 staff members including housekeeping and reception',
    },
    {
      id: 'EXP-005',
      title: 'Online Marketing (Facebook + Google Ads)',
      category: 'marketing',
      amount: 25000,
      date: '2026-06-08',
      status: 'paid',
      description: 'June digital marketing campaigns',
    },
    {
      id: 'EXP-006',
      title: 'Kitchen Supplies & Groceries',
      category: 'guest-supplies',
      amount: 12000,
      date: '2026-06-15',
      status: 'paid',
    },
  ],
  investors: [
    {
      id: 'INV-001',
      investorName: 'Zainab Enterprises',
      amount: 2500000,
      date: '2025-01-15',
      equityPercentage: 35,
      notes: 'Lead investor — founding partner',
    },
    {
      id: 'INV-002',
      investorName: 'Ali Brothers Holdings',
      amount: 1500000,
      date: '2025-03-20',
      equityPercentage: 20,
      notes: 'Secondary investor',
    },
    {
      id: 'INV-003',
      investorName: 'National Hospitality Fund',
      amount: 1000000,
      date: '2025-06-01',
      equityPercentage: 15,
      notes: 'Tourism fund contribution',
    },
  ],
  maintenanceIssues: [
    {
      id: 'MNT-001',
      title: 'AC Compressor Failure',
      roomId: '302',
      priority: 'urgent',
      status: 'in-progress',
      reportedDate: '2026-06-12',
      assignedTo: 'Usman Electricals',
      notes: 'Parts ordered. ETA 2 days.',
    },
    {
      id: 'MNT-002',
      title: 'Bathroom Tap Dripping',
      roomId: '101',
      priority: 'low',
      status: 'reported',
      reportedDate: '2026-06-20',
      notes: 'Minor leak in shower tap.',
    },
    {
      id: 'MNT-003',
      title: 'TV Remote Not Working',
      roomId: '202',
      priority: 'low',
      status: 'fixed',
      reportedDate: '2026-06-18',
      assignedTo: 'Reception Team',
      notes: 'Battery replaced. Resolved.',
    },
  ],
  extraRevenueEntries: [
    {
      id: 'REV-001',
      title: 'Restaurant F&B — June Week 3',
      amount: 32000,
      date: '2026-06-22',
      category: 'extra-charges',
      notes: 'In-room dining + lobby restaurant revenue',
    },
    {
      id: 'REV-002',
      title: 'Event Hall Rental — Corporate Meet',
      amount: 50000,
      date: '2026-06-15',
      category: 'direct',
      notes: 'Full day corporate event booking',
    },
    {
      id: 'REV-003',
      title: 'Airport Transfer Services',
      amount: 8500,
      date: '2026-06-27',
      category: 'extra-charges',
    },
  ],
  auditLogs: [],
};

export const DEMO_USER = {
  email: 'demo@zavarihaus.com',
  role: 'owner-admin' as const,
};

export const DEMO_TOKEN = 'DEMO_MODE_TOKEN_VHA';
